#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 默认把非敏感申请信息保存到专用本地文件，避免污染通用 .env。
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE=".env.signpath.local"
fi

TOTAL_STAGES=6

banner "QuickNote · SignPath Foundation 申请向导"

stage "确认公开仓库与 MIT 许可证"
say "SignPath Foundation 只接受完整开源且已公开发行的项目。"
open_url "https://github.com/eelevenn/quicknote"
step "确认仓库标题旁显示 Public，而不是 Private。"
step "打开 LICENSE，确认内容为 MIT License。"
if ! confirm "仓库和许可证都已公开可见？"; then
  warn "先完成公开和许可证变更，再重新运行本向导。"
  exit 1
fi
write_env SIGNPATH_REPOSITORY_URL "https://github.com/eelevenn/quicknote"
write_env SIGNPATH_LICENSE "MIT"

stage "启用账户多因素认证"
say "SignPath 要求所有提交者、审查者和签名批准人启用多因素认证。"
open_url "https://github.com/settings/security"
step "在 Access → Password and authentication 中找到 Two-factor authentication。"
step "确认状态为 On；若未启用，按页面指引添加身份验证器和恢复代码。"
warn "恢复代码应保存到你自己的密码管理器，绝不要粘贴到本向导或仓库。"
if ! confirm "GitHub 两步验证已经启用？"; then
  warn "两步验证是申请硬条件，完成后再继续。"
  exit 1
fi

stage "确认已有合格公开发行版"
say "官方条款要求项目已经以未来需要签名的形式发布。仅有源码标签通常不够。"
open_url "https://github.com/eelevenn/quicknote/releases"
step "确认至少有一个公开 QuickNote Windows 发行版，并包含项目说明和下载文件。"
step "不要为了申请而发布未通过 Issue #22 发布门槛的二进制。"
if ! confirm "已有满足上述条件的公开 Windows 发行版？"; then
  warn "当前应先完成 Issue #22；有合格 Release 后再重新运行本向导。"
  exit 1
fi
ask SIGNPATH_RELEASE_URL "粘贴公开 Release URL："
ask SIGNPATH_RELEASE_VERSION "输入该 Release 版本号（例如 0.1.0）："
write_env SIGNPATH_RELEASE_URL "$SIGNPATH_RELEASE_URL"
write_env SIGNPATH_RELEASE_VERSION "$SIGNPATH_RELEASE_VERSION"

stage "核对 SignPath Foundation 条款"
open_url "https://signpath.org/terms.html"
step "核对 OSS License、No proprietary code、Maintained、Released 和 Documented 条件。"
step "核对每次签名人工批准、可验证构建、团队角色、隐私说明和卸载要求。"
step "阅读仓库中的 CODE_SIGNING_POLICY.md、PRIVACY.md 与 THIRD_PARTY_NOTICES.md。"
warn "QuickNote 只能提交自己源码构建的 EXE、sidecar 和 MSI；不得把上游模型冒充为 QuickNote 产物签名。"
if ! confirm "你接受条款，并确认项目当前满足这些条件？"; then
  warn "不要提交不满足条件的申请；先修复对应前置项。"
  exit 1
fi

stage "填写并提交申请表"
ask SIGNPATH_CONTACT_EMAIL "输入用于接收 SignPath 审核邮件的邮箱："
open_url "https://signpath.org/apply.html"
step "在联系人字段填写你的真实姓名与上面的联系邮箱。"
step "项目名称填写 QuickNote；仓库填写 https://github.com/eelevenn/quicknote。"
step "许可证填写 MIT；公开发行版填写刚才记录的 Release URL。"
step "项目说明填写：Local-first quick note and reminder application for Windows 11."
step "构建系统填写 GitHub Actions；签名目标说明为 QuickNote EXE、QuickNote-owned SenseVoice sidecar EXE and per-user MSI。"
step "若表单字段名称略有变化，按上述语义对应填写；不要声明模型文件由 QuickNote 拥有。"
step "确认隐私和条款复选框后，点击 Submit。"
pause "看到提交成功页面或收到确认邮件后按 Enter"
write_env SIGNPATH_CONTACT_EMAIL "$SIGNPATH_CONTACT_EMAIL"

stage "记录申请并等待审核"
ask SIGNPATH_APPLICATION_DATE "输入申请日期（YYYY-MM-DD）："
ask SIGNPATH_CONFIRMATION "粘贴确认邮件主题或申请编号；若没有编号可填写 submitted："
write_env SIGNPATH_APPLICATION_DATE "$SIGNPATH_APPLICATION_DATE"
write_env SIGNPATH_CONFIRMATION "$SIGNPATH_CONFIRMATION"
say "审核通过前不需要创建 PFX、上传私钥或购买证书。"
say "收到批准邮件后，请回到 Issue #22；下一步是配置 SignPath 项目、可信构建与 GitHub Actions。"

finish
